baseURL = "https://vilcagamarracf.github.io/"
languageCode = "es-PE"
title = "Cesar Vilca"
theme = "PaperMod"

[params]
  description = "Agricultura de Precisión, Teledetección y Programación"
  author = "Cesar Vilca"
  ShowReadingTime = true
  ShowShareButtons = false