baseURL = "https://vilcagamarracf.github.io/"
languageCode = "es-PE"
title = "Cesar Vilca"
theme = "PaperMod"

[params]
  description = "Agricultura de Precisión, Teledetección y Programación"
  author = "Cesar Vilca"
  ShowReadingTime = true
  ShowShareButtons = false
  customCSS = ["css/extended/custom.css"]

  [params.profileMode]
    enabled = true
    title = "Cesar Vilca"
    subtitle = "Agricultura de Precisión · Teledetección · Estadística · Programación"
    imageUrl = "/img/foto_perfil_vf.jpg"

    [[params.profileMode.buttons]]
      name = "Blog"
      url = "/posts/"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/vilcagamarracf"

[[params.socialIcons]]
  name = "x"
  url = "https://twitter.com/vilcagamarracf"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/cesarvilca/"

[[params.socialIcons]]
  name = "googlescholar"
  url = "https://scholar.google.com/citations?user=GDn7H2wAAAAJ&hl=en"

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menus.main]]
  name = "Blog"
  url = "/posts/"
  weight = 2